In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

training_data = pd.read_csv('data/mnist_train.csv')

/Users/faridjamshid/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [6]:
training_data = np.array(training_data)
m, n = training_data.shape

Y_train = training_data[:,0]
X_train = training_data[:, 1:].T

X_train = X_train / 255

In [ ]:
def ReLU(Z):
    return np.maximum(Z, 0)

def init_params():
    W1 = np.random.rand(15, 784) - 0.5
    b1 = np.random.rand(15, 1) - 0.5
    W2 = np.random.rand(10, 15) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU_deriv(Z):
    return Z > 0

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

def forw_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def back_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

In [8]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forw_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print(f'iteration: {i}')
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [9]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.1, 500)

iteration: 0
[1 1 1 ... 1 1 1] [5 0 4 ... 5 6 8]
0.09068333333333334
iteration: 10
[1 3 1 ... 9 9 3] [5 0 4 ... 5 6 8]
0.1786
iteration: 20
[1 7 4 ... 9 0 7] [5 0 4 ... 5 6 8]
0.29741666666666666
iteration: 30
[1 0 4 ... 9 0 7] [5 0 4 ... 5 6 8]
0.3799666666666667
iteration: 40
[1 0 4 ... 9 0 7] [5 0 4 ... 5 6 8]
0.44116666666666665
iteration: 50
[3 0 4 ... 9 0 7] [5 0 4 ... 5 6 8]
0.49485
iteration: 60
[3 0 4 ... 9 0 7] [5 0 4 ... 5 6 8]
0.545
iteration: 70
[3 0 4 ... 9 0 8] [5 0 4 ... 5 6 8]
0.5888333333333333
iteration: 80
[3 0 4 ... 9 0 8] [5 0 4 ... 5 6 8]
0.6257333333333334
iteration: 90
[3 0 4 ... 9 0 8] [5 0 4 ... 5 6 8]
0.6542
iteration: 100
[3 0 4 ... 9 0 8] [5 0 4 ... 5 6 8]
0.6787166666666666
iteration: 110
[3 0 4 ... 9 0 8] [5 0 4 ... 5 6 8]
0.6972333333333334
iteration: 120
[3 0 4 ... 9 0 8] [5 0 4 ... 5 6 8]
0.71275
iteration: 130
[3 0 4 ... 9 0 8] [5 0 4 ... 5 6 8]
0.7252666666666666
iteration: 140
[3 0 4 ... 9 0 8] [5 0 4 ... 5 6 8]
0.7360333333333333
iteration: 150
[3